-- shows the number of posts per user ordered by the most active to the least one.
SELECT USERS.USERSfirstname, USERS.USERSlastname, COUNT(USERS.USERSfirstname) AS POSTS
FROM USERS, POSTS, POSTMESSAGES, POSTSIMGPATH
WHERE POSTS.IDPOSTS = POSTMESSAGES.POSTS_IDPOSTS
AND POSTS.idPOSTS = POSTSIMGPATH.POSTS_idPOSTS
AND POSTS.USERS_idUSERS = USERS.idUSERS
GROUP BY USERS.USERSfirstname
ORDER BY POSTS DESC
LIMIT 0 , 30
