-- shows the number of posts per user ordered by the most active to the least one.
SELECT USERS.USERSfirstname, USERS.USERSlastname, COUNT(USERS.USERSfirstname) AS POSTS
FROM USERS, POSTS, POSTMESSAGES, POSTSIMGPATH
WHERE POSTS.IDPOSTS = POSTMESSAGES.POSTS_IDPOSTS
AND POSTS.idPOSTS = POSTSIMGPATH.POSTS_idPOSTS
AND POSTS.USERS_idUSERS = USERS.idUSERS
GROUP BY USERS.USERSfirstname
ORDER BY POSTS DESC
LIMIT 0 , 30

-- shows the number of posts per Date ordered by the number of posts desc. 
SELECT SUBSTR(POSTS.POSTScreatedAt, 1,10) AS createdAt, 
COUNT(POSTS.POSTScreatedAt) AS POSTS
FROM USERS, POSTS, POSTMESSAGES, POSTSIMGPATH
WHERE POSTS.IDPOSTS = POSTMESSAGES.POSTS_IDPOSTS
AND POSTS.idPOSTS = POSTSIMGPATH.POSTS_idPOSTS
AND POSTS.USERS_idUSERS = USERS.idUSERS
GROUP BY createdAt
ORDER BY POSTS DESC
LIMIT 25


-- update exmaple
update `POSTS` set `POSTScreatedAt` = '2019-11-15 00:00:00'
WHERE  `POSTScreatedAt` =  '0000-00-00 00:00:00'